# Generated by Django 5.0.2 on 2024-04-10 22:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("bidwin", "0004_user_join_date"),
    ]

    operations = [
        migrations.CreateModel(
            name="Item",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=500)),
                ("price", models.FloatField(default=0.0)),
                ("description", models.CharField(max_length=3000)),
                ("release_date", models.DateTimeField()),
                ("created_date", models.DateTimeField()),
                (
                    "owner",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="owened_item",
                        to="bidwin.user",
                    ),
                ),
            ],
        ),
    ]
