# Generated by Django 5.0.2 on 2024-04-12 12:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bidwin", "0004_user_join_date"),
        ("item", "0002_comment"),
    ]

    operations = [
        migrations.CreateModel(
            name="Participate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("suggested_price", models.FloatField(default=0.0)),
                ("date_time", models.DateTimeField()),
                (
                    "item_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="item.item"
                    ),
                ),
                (
                    "owner_id",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE, to="bidwin.user"
                    ),
                ),
            ],
        ),
    ]
