# Generated by Django 5.0.2 on 2024-04-18 22:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bidwin", "0008_remove_verificationcode_id_and_more"),
        ("item", "0003_participate"),
    ]

    operations = [
        migrations.AlterField(
            model_name="item",
            name="owner",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="items",
                to="bidwin.user",
            ),
        ),
    ]
