# Generated by Django 5.0.2 on 2024-04-18 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bidwin", "0008_remove_verificationcode_id_and_more"),
        ("item", "0004_alter_item_owner"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="participate",
            name="owner_id",
        ),
        migrations.AddField(
            model_name="participate",
            name="owner_id",
            field=models.ManyToManyField(
                blank=True, related_name="participent_items", to="bidwin.user"
            ),
        ),
    ]
