# Generated by Django 5.0.2 on 2024-04-18 22:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("item", "0005_remove_participate_owner_id_participate_owner_id"),
    ]

    operations = [
        migrations.RenameField(
            model_name="participate",
            old_name="owner_id",
            new_name="owner",
        ),
    ]
