# Generated by Django 5.0.2 on 2024-05-09 11:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bidwin", "0013_remove_user_address_remove_user_groups_and_more"),
        ("item", "0007_itemimage_winner_item"),
    ]

    operations = [
        migrations.AlterField(
            model_name="comment",
            name="owner_id",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE, to="bidwin.userprofile"
            ),
        ),
        migrations.AlterField(
            model_name="item",
            name="owner",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="items",
                to="bidwin.userprofile",
            ),
        ),
        migrations.AlterField(
            model_name="participate",
            name="owner",
            field=models.ManyToManyField(
                blank=True, related_name="participent_items", to="bidwin.userprofile"
            ),
        ),
        migrations.AlterField(
            model_name="winner_item",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="won_items",
                to="bidwin.userprofile",
            ),
        ),
    ]
