# Generated by Django 5.0.2 on 2024-05-14 11:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("item", "0011_item_expiration_date"),
    ]

    operations = [
        migrations.CreateModel(
            name="Console",
            fields=[
                (
                    "item_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="item.item",
                    ),
                ),
                ("generation", models.CharField(max_length=100)),
                ("manufacturer", models.CharField(max_length=100)),
            ],
            bases=("item.item",),
        ),
        migrations.CreateModel(
            name="Laptop",
            fields=[
                (
                    "item_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="item.item",
                    ),
                ),
                ("cpu", models.CharField(max_length=100)),
                ("gpu", models.CharField(max_length=100)),
            ],
            bases=("item.item",),
        ),
        migrations.CreateModel(
            name="Phone",
            fields=[
                (
                    "item_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="item.item",
                    ),
                ),
                ("sim_number", models.IntegerField()),
                ("camera", models.IntegerField()),
            ],
            bases=("item.item",),
        ),
    ]
