# Generated by Django 5.0.2 on 2024-05-14 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("item", "0013_alter_item_owner"),
    ]

    operations = [
        migrations.AddField(
            model_name="console",
            name="controler_number",
            field=models.CharField(default="0", max_length=2),
        ),
        migrations.AddField(
            model_name="item",
            name="brand",
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AddField(
            model_name="item",
            name="core_number",
            field=models.CharField(default=None, max_length=2),
        ),
        migrations.AddField(
            model_name="laptop",
            name="os",
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AddField(
            model_name="phone",
            name="os",
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AlterField(
            model_name="laptop",
            name="cpu",
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AlterField(
            model_name="laptop",
            name="gpu",
            field=models.CharField(default=None, max_length=100),
        ),
    ]
