# Generated by Django 5.0.2 on 2024-05-15 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("item", "0014_console_controler_number_item_brand_item_core_number_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="itemimage",
            name="image",
            field=models.ImageField(upload_to="item_images/item/"),
        ),
    ]
