# Generated by Django 5.0.2 on 2024-05-16 08:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("item", "0015_alter_itemimage_image"),
    ]

    operations = [
        migrations.RenameField(
            model_name="console",
            old_name="manufacturer",
            new_name="region",
        ),
    ]
