# Generated by Django 5.0.2 on 2024-05-16 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("item", "0016_rename_manufacturer_console_region"),
    ]

    operations = [
        migrations.AddField(
            model_name="item",
            name="link",
            field=models.CharField(default=None, max_length=100),
        ),
    ]
