# Generated by Django 5.0.2 on 2024-05-16 08:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("item", "0017_item_link"),
    ]

    operations = [
        migrations.RenameField(
            model_name="comment",
            old_name="item_id",
            new_name="item",
        ),
        migrations.RenameField(
            model_name="participate",
            old_name="item_id",
            new_name="item",
        ),
    ]
