# Generated by Django 5.0.2 on 2024-05-16 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("item", "0018_rename_item_id_comment_item_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="item",
            name="link",
            field=models.CharField(max_length=100, null=True),
        ),
    ]
