# Generated by Django 5.0.2 on 2024-05-16 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("item", "0019_alter_item_link"),
    ]

    operations = [
        migrations.AddField(
            model_name="item",
            name="group",
            field=models.CharField(max_length=100, null=True),
        ),
    ]
