# Generated by Django 5.0.2 on 2024-03-15 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "username",
                    models.CharField(default="non", max_length=200, unique=True),
                ),
                ("email", models.EmailField(max_length=254, null=True, unique=True)),
                ("name", models.CharField(max_length=300)),
                ("last_name", models.CharField(max_length=300)),
                ("wallet", models.FloatField(default=0.0)),
                ("password", models.CharField(max_length=1000)),
            ],
        ),
    ]
