# Generated by Django 5.0.2 on 2024-04-10 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bidwin", "0002_user_phone"),
    ]

    operations = [
        migrations.CreateModel(
            name="Parameter",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Name", models.CharField(max_length=220)),
                ("Value", models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name="ReturnedData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("MessageId", models.IntegerField()),
                ("Cost", models.DecimalField(decimal_places=1, max_digits=2)),
            ],
        ),
        migrations.AddField(
            model_name="user",
            name="national_code",
            field=models.CharField(default="Non", max_length=10),
        ),
        migrations.AlterField(
            model_name="user",
            name="username",
            field=models.CharField(default="Non", max_length=200, unique=True),
        ),
    ]
