# Generated by Django 5.0.2 on 2024-04-10 21:55

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bidwin", "0003_parameter_returneddata_user_national_code_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="join_date",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
