# Generated by Django 5.0.2 on 2024-04-17 10:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("bidwin", "0005_verificationcode"),
    ]

    operations = [
        migrations.RenameField(
            model_name="verificationcode",
            old_name="created_at",
            new_name="expired_at",
        ),
    ]
