# Generated by Django 5.0.2 on 2024-04-17 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bidwin", "0006_rename_created_at_verificationcode_expired_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="verificationcode",
            name="code",
            field=models.IntegerField(),
        ),
    ]
