# Generated by Django 5.0.2 on 2024-04-17 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bidwin", "0007_alter_verificationcode_code"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="verificationcode",
            name="id",
        ),
        migrations.AlterField(
            model_name="verificationcode",
            name="mobile_number",
            field=models.CharField(
                max_length=20, primary_key=True, serialize=False, unique=True
            ),
        ),
    ]
