# Generated by Django 5.0.2 on 2024-05-07 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bidwin", "0009_feedback"),
    ]

    operations = [
        migrations.CreateModel(
            name="Address",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("state", models.CharField(max_length=300)),
                ("city", models.CharField(max_length=300)),
                ("address_detail", models.CharField(max_length=1000)),
                ("plaque", models.CharField(max_length=5)),
                ("floor", models.CharField(max_length=2)),
                ("postal_code", models.CharField(max_length=10)),
                ("land_line_phone", models.CharField(max_length=12)),
            ],
        ),
    ]
