# Generated by Django 5.0.2 on 2024-05-14 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bidwin", "0015_alter_feedback_owner"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="is_premium",
            field=models.BooleanField(default=False),
        ),
    ]
