# Generated by Django 5.0.2 on 2024-05-16 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bidwin", "0017_account"),
    ]

    operations = [
        migrations.AlterField(
            model_name="account",
            name="Reference_Number",
            field=models.CharField(
                blank=True,
                default="bnxxumpb4n",
                editable=False,
                max_length=10,
                unique=True,
            ),
        ),
    ]
