# Generated by Django 5.0.2 on 2024-05-18 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bidwin", "0022_alter_account_reference_number"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="dob",
            field=models.CharField(default=None, max_length=15),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="gender",
            field=models.CharField(default=None, max_length=15),
        ),
        migrations.AlterField(
            model_name="account",
            name="Reference_Number",
            field=models.CharField(
                blank=True,
                default="ztgp6g5qpd",
                editable=False,
                max_length=10,
                unique=True,
            ),
        ),
    ]
