# Generated by Django 5.0.2 on 2024-05-18 16:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bidwin", "0023_userprofile_dob_userprofile_gender_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Discount",
            fields=[
                (
                    "code",
                    models.CharField(
                        max_length=6, primary_key=True, serialize=False, unique=True
                    ),
                ),
                ("discount_percent", models.FloatField(default=0.0)),
            ],
        ),
        migrations.RemoveField(
            model_name="account",
            name="Reference_Number",
        ),
        migrations.RemoveField(
            model_name="account",
            name="account_number",
        ),
        migrations.RemoveField(
            model_name="account",
            name="balance",
        ),
        migrations.RemoveField(
            model_name="userprofile",
            name="wallet",
        ),
        migrations.AddField(
            model_name="account",
            name="bank_account_accepted",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="account",
            name="bank_name",
            field=models.CharField(default=None, max_length=255),
        ),
        migrations.AddField(
            model_name="account",
            name="inventory_money",
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="account",
            name="locked_money",
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="account",
            name="penalty_money",
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="account",
            name="pending_money",
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="account",
            name="shaba_number",
            field=models.CharField(default=0, max_length=24),
        ),
        migrations.AddField(
            model_name="account",
            name="withdrawn_money",
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="account",
            name="withdrawn_requested",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="image",
            field=models.ImageField(
                default=None, upload_to="item_images/user_profile/"
            ),
        ),
        migrations.AlterField(
            model_name="account",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="accounts",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.CreateModel(
            name="SpecialAccountDetails",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date_of_start", models.DateField()),
                ("date_of_end", models.DateField()),
                ("price", models.BigIntegerField(default=0)),
                ("duration", models.IntegerField(default=0)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="special_account_details",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="WithdrawnDetails",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("amount", models.BigIntegerField(default=0)),
                ("datetime_of_accept", models.DateTimeField()),
                ("datetime_of_clearing", models.DateTimeField()),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="withdrawn_details",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
