# Generated by Django 5.0.2 on 2024-05-18 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bidwin", "0024_discount_remove_account_reference_number_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userprofile",
            name="image",
            field=models.ImageField(upload_to="item_images/item/"),
        ),
    ]
