# Generated by Django 5.0.2 on 2024-05-18 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bidwin", "0025_alter_userprofile_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userprofile",
            name="image",
            field=models.ImageField(upload_to="item_images/user_profile/"),
        ),
    ]
