# Generated by Django 5.0.2 on 2024-05-18 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bidwin", "0027_alter_userprofile_dob_alter_userprofile_gender"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="address_available",
            field=models.BooleanField(default=False),
        ),
    ]
