# Generated by Django 5.0.2 on 2024-06-19 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bidwin", "0029_alter_address_address_detail_alter_address_city_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="rate",
            field=models.FloatField(default=0.0),
        ),
    ]
